### ISSUE TITLE
Indicator in top left not reseting after ending a contract.

### ISSUE THREAD

**Issue by Hambuergesito** [geel9/runelite-hunter-rumours#40]
Issue with the contract number indicator, everything works fine. But when you finish a contract and get a new one the icon doesn't reset to 0. 
![image](https://github.com/geel9/runelite-hunter-rumours/assets/123756748/f1fb0f74-8f52-494a-b5db-bd7e91f35dd0)

**Comment by Tasoril** [comment]
I ran into this issue as well and was coming to report it. For me, the issue was I was juggling my block list and did a rumour for the novice guild hunter, and his dialog for completion isn't caught in the code.

I created a pull request that incorporates his completion message into the existing code. #41

**Comment by DapperMickie** [comment]
After fixing up the PR a little bit, I merged it, which means this will be fixed in the next update!

P.S.
This might take a while, because we're working on some other features before we update the plugin.
